### ISSUE TITLE
Npm build fails in CentOS 5.11 while compiling optipng

### ISSUE THREAD

**Issue by dipayanb** [gruntjs/grunt-contrib-imagemin#267]
I am trying to install grunt-contrib-imagemin 0.9.1. I am getting the following error:

```
> node lib/install.js


     warn : The `optipng` binary doesn't seem to work correctly
     warn : optipng pre-build test failed
     info : compiling from source
    error : Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

The following are the enviroment details:

```
OS: CentOS 5.11
node version: v0.10.26
npm version: 2.1.7
```

Previously I had tried with some older version of the grunt package, and it failed in installing gifsicle too. But after updating to 0.9.1 those issues got solved.

Please show me a way out, I am stuck with this. Thanks a lot in advance.

**Comment by rmldsky** [comment]
To people facing this problem, check if you have `libpng-dev` (or `libpng-devel` depending on Linux distro) installed on your system.

**Comment by maboiteaspam** [comment]
>  Home we can resolve definitively this problem? :-(

node pre gyp may be the solution your looking for.

**Comment by kevva** [comment]
> To people facing this problem, check if you have libpng-dev (or libpng-devel depending on Linux distro) installed on your system.

**Comment by shrpne** [comment]
I get this error on freebsd 10
tried to install /usr/ports/graphics/png (seems it is libpng) this not helped.

```
/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng 0.7.1 does not satisfy the version requirement of >=0.7.5
  Б ═ optipng pre-build test failed
  Б└╧ compiling from source
  Б°√ Error: ./configure --with-system-zlib --prefix="/usr/local/www/artel-nk.ru/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/usr/local/www/artel-nk.ru/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
Command failed: usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file ... target_directory

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

> pngquant-bin@1.0.1 postinstall /usr/local/www/artel-nk.ru/node_modules/pngquant-bin
> node lib/install.js

Б ═ pre-build test failed, compiling from source...
Б°√ pngquant failed to build, make sure that libpng-dev is installed

{ [Error: Command failed: make: "/usr/local/www/artel-nk.ru/node_modules/pngquant-bin/6194e695-1952-4ae0-8f3a-55647d196f82/Makefile" line 9: Missing dependency operator
make: "/usr/local/www/artel-nk.ru/node_modules/pngquant-bin/6194e695-1952-4ae0-8f3a-55647d196f82/Makefile" line 11: Need an operator
make: "/usr/local/www/artel-nk.ru/node_modules/pngquant-bin/6194e695-1952-4ae0-8f3a-55647d196f82/Makefile" line 61: Missing dependency operator
make: "/usr/local/www/artel-nk.ru/node_modules/pngquant-bin/6194e695-1952-4ae0-8f3a-55647d196f82/Makefile" line 64: Need an operator
make: Fatal errors encountered -- cannot continue] killed: false, code: 1, signal: null }
grunt-contrib-imagemin@0.9.3 node_modules/grunt-contrib-imagemin
```

**Comment by fredrikekelund** [comment]
Could the `libpng-dev` dependency get a mention in the README? I encountered the same problem on an ARM server, would be nice to surface that information a bit

**Comment by uniquelau** [comment]
On Alpine Linux I'm having to do:

apk add --no-cache zlib zlib-dev libpng libpng-dev libwebp libwebp-dev libjpeg-turbo libjpeg-turbo-dev nasm build-base automake autoconf file && npm install

**Comment by christianhaller** [comment]
Did you try this? https://github.com/smart-devs/pngquant-lamda
