### ISSUE TITLE
I have a problem when installing

### ISSUE THREAD

**Issue by in-in** [gruntjs/grunt-contrib-imagemin#284]
```bash
➜  hexagon  npm install grunt-contrib-imagemin --save-dev                                                           
npm WARN package.json hexagon@1.0.0 No repository field.
npm WARN package.json hexagon@1.0.0 No README data
\
> pngquant-bin@2.0.3 postinstall /media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant` binary. Make sure it has the right permissions.
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

> optipng-bin@2.0.4 postinstall /media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng` binary. Make sure it has the right permissions.
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
Command failed: pngrtran.c:97:1: warning: ‘png_rtran_ok’ defined but not used [-Wunused-function]
 png_rtran_ok(png_structrp png_ptr, int need_IHDR)
 ^
pngxmem.c: In function ‘pngx_malloc_rows_extended’:
pngxmem.c:37:4: warning: comparison is always false due to limited range of data type [-Wtype-limits]
    if (row_size == 0 || height > (pngx_alloc_size_t)(-1) / sizeof(png_bytep))
    ^
rm: cannot remove ‘/media/id/2B4FED33394C4BBB/15.’: Is a directory
make[1]: [install] Error 1 (ignored)
rm: cannot remove ‘/media/id/2B4FED33394C4BBB/15.’: Is a directory
make[1]: [install] Error 1 (ignored)
cp: omitting directory ‘/media/id/2B4FED33394C4BBB/15.’
make[1]: *** [install] Error 1
make: *** [install] Error 2

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

> jpegtran-bin@2.0.2 postinstall /media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran` binary. Make sure it has the right permissions.
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --disable-shared --prefix="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install
Command failed: sed: read error on /media/id/2B4FED33394C4BBB/15.: Is a directory
./configure: line 1487: .: /media/id/2B4FED33394C4BBB/15.: is a directory
sed: read error on /media/id/2B4FED33394C4BBB/15.: Is a directory
./configure: line 1487: .: /media/id/2B4FED33394C4BBB/15.: is a directory
configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

> gifsicle@2.0.1 postinstall /media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ Couldn't execute the `/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle` binary. Make sure it has the right permissions.
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" --bindir="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" && make install
Command failed: /bin/sh: 1: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

grunt-contrib-imagemin@0.9.2 node_modules/grunt-contrib-imagemin
├── async@0.9.0
├── pretty-bytes@1.0.2 (get-stdin@1.0.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── imagemin@3.1.0 (get-stdin@3.0.2, optional@0.1.2, stream-combiner@0.2.1, vinyl@0.4.6, concat-stream@1.4.7, through2@0.6.3, meow@2.1.0, imagemin-svgo@4.0.2, vinyl-fs@0.3.13, imagemin-pngquant@4.0.0, imagemin-optipng@4.2.0, imagemin-jpegtran@4.0.0, imagemin-gifsicle@4.1.0)
➜  hexagon 
```

**Comment by maboiteaspam** [comment]
check the error messages and let us know if they seems justified.
For example, see   ✖ Error: pngquant failed to build, make sure that libpng-dev is installed

**Comment by in-in** [comment]
I do not have this library libpng-dev. But I tried another libpng12-dev. 
```bash
➜  hexagon   npm install grunt-contrib-imagemin --save-dev  
npm WARN package.json hexagon@1.0.0 No repository field.
npm WARN package.json hexagon@1.0.0 No README data
|
> optipng-bin@2.0.4 postinstall /media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng` binary. Make sure it has the right permissions.
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
Command failed: pngrtran.c:97:1: warning: ‘png_rtran_ok’ defined but not used [-Wunused-function]
 png_rtran_ok(png_structrp png_ptr, int need_IHDR)
 ^
pngxmem.c: In function ‘pngx_malloc_rows_extended’:
pngxmem.c:37:4: warning: comparison is always false due to limited range of data type [-Wtype-limits]
    if (row_size == 0 || height > (pngx_alloc_size_t)(-1) / sizeof(png_bytep))
    ^
rm: cannot remove ‘/media/id/2B4FED33394C4BBB/15.’: Is a directory
make[1]: [install] Error 1 (ignored)
rm: cannot remove ‘/media/id/2B4FED33394C4BBB/15.’: Is a directory
make[1]: [install] Error 1 (ignored)
cp: omitting directory ‘/media/id/2B4FED33394C4BBB/15.’
make[1]: *** [install] Error 1
make: *** [install] Error 2

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

> pngquant-bin@2.0.3 postinstall /media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant` binary. Make sure it has the right permissions.
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

> gifsicle@2.0.1 postinstall /media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ Couldn't execute the `/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle` binary. Make sure it has the right permissions.
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" --bindir="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" && make install
Command failed: /bin/sh: 1: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)


> jpegtran-bin@2.0.2 postinstall /media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran` binary. Make sure it has the right permissions.
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --disable-shared --prefix="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/media/id/2B4FED33394C4BBB/15. webdev/site/hexagon/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install
Command failed: sed: read error on /media/id/2B4FED33394C4BBB/15.: Is a directory
./configure: line 1487: .: /media/id/2B4FED33394C4BBB/15.: is a directory
sed: read error on /media/id/2B4FED33394C4BBB/15.: Is a directory
./configure: line 1487: .: /media/id/2B4FED33394C4BBB/15.: is a directory
configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
grunt-contrib-imagemin@0.9.2 node_modules/grunt-contrib-imagemin
├── async@0.9.0
├── pretty-bytes@1.0.2 (get-stdin@1.0.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
└── imagemin@3.1.0 (get-stdin@3.0.2, optional@0.1.2, stream-combiner@0.2.1, vinyl@0.4.6, through2@0.6.3, concat-stream@1.4.7, meow@2.1.0, vinyl-fs@0.3.13, imagemin-svgo@4.0.2, imagemin-optipng@4.2.0, imagemin-pngquant@4.0.0, imagemin-gifsicle@4.1.0, imagemin-jpegtran@4.0.0)
➜  hexagon  
```

**Comment by maboiteaspam** [comment]
which system are you building on ?

**Comment by in-in** [comment]
Linux Mint 17.1 64bit

**Comment by maboiteaspam** [comment]
weird. That s debian based distro right ?

I d suggest also you forward your bug to https://github.com/imagemin/optipng-bin/issues / https://github.com/imagemin/jpegtran-bin / https://github.com/imagemin/gifsicle-bin as it is more specifically related to those packages than grunt-contrib-img-min itself.

**Comment by in-in** [comment]
Yes weird. 
I installed the same distro on my VirtualBox. Then tried again grunt-contrib-imagemin and installation complete correctly. Sorry problem on my system, not in the grunt-contrib-imagemin.
```bash
➜  test_imagemin  npm install grunt-contrib-imagemin --save-dev
npm WARN package.json test_imagemin@1.0.0 No repository field.
npm WARN package.json test_imagemin@1.0.0 No README data
npm WARN engine imagemin@3.1.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.36","npm":"1.4.28"})
\
> optipng-bin@2.0.4 postinstall /home/page/Desktop/test_imagemin/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> gifsicle@2.0.1 postinstall /home/page/Desktop/test_imagemin/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully


> pngquant-bin@2.0.3 postinstall /home/page/Desktop/test_imagemin/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully

> jpegtran-bin@2.0.2 postinstall /home/page/Desktop/test_imagemin/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully
grunt-contrib-imagemin@0.9.2 node_modules/grunt-contrib-imagemin
├── async@0.9.0
├── pretty-bytes@1.0.2 (get-stdin@1.0.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── imagemin@3.1.0 (get-stdin@3.0.2, optional@0.1.2, stream-combiner@0.2.1, vinyl@0.4.6, through2@0.6.3, meow@2.1.0, concat-stream@1.4.7, imagemin-svgo@4.0.2, vinyl-fs@0.3.13, imagemin-optipng@4.2.0, imagemin-gifsicle@4.1.0, imagemin-pngquant@4.0.0, imagemin-jpegtran@4.0.0)
➜  test_imagemin
```

**Comment by maboiteaspam** [comment]
Don t forget to close it if that works for you !

**Comment by kraftner** [comment]
related https://github.com/imagemin/optipng-bin/issues/45
