### ISSUE TITLE
Getting npm install warning

### ISSUE THREAD

**Issue by kevin-abl** [gruntjs/grunt-contrib-imagemin#305]
Got the following warning on imagemin install.  It seems related to this issue in the underlying project, which has now updated to version 3.2:

https://github.com/imagemin/imagemin/issues/104

```
MacBook-Air:Dashboard me$ npm install grunt-contrib-imagemin --save-dev
|
> optipng-bin@3.0.2 postinstall /Users/me/Projects/thingy/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

|
module.js:340
    throw err;
          ^
Error: Cannot find module '../../object/valid-value'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/me/Projects/thingy/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es5-ext/array/#/clear.js:7:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

> jpegtran-bin@3.0.2 postinstall /Users/me/Projects/thingy/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
```

**Comment by kevva** [comment]
See https://github.com/imagemin/imagemin/issues/104.
