### ISSUE TITLE
ENOENT error with Yeoman build

### ISSUE THREAD

**Issue by herrjosua** [gruntjs/grunt-contrib-imagemin#308]
I am encountering an error while trying to build my project that include the grunt-contrib-imagemin library. My project is built using the Yeoman AngularJS generator (https://github.com/yeoman/generator-angular)

I am using Node v0.12.0, NPM v2.5.1, Yeoman 1.47, Bower 1.4.1, Grunt-Cli v0.1.13 and grunt v0.4.5

Below is the output from doing a npm install:

```
> optipng-bin@3.0.2 postinstall C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules
\optipng-bin

> node lib/install.js

  ‼ Request to https://raw.githubusercontent.com/imagemin/optipng-bin/3.0.2/vendor/win/optipng.exe failed
  ‼ optipng pre-build test failed
  i compiling from source
 Error: ./configure --with-system-zlib --prefix="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-opt
ipng\node_modules\optipng-bin\vendor" --bindir="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-opti
png\node_modules\optipng-bin\vendor" && make install
Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --with-system-zlib --prefix="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node
_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" --bindir="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_
modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor""
'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)|
> jpegtran-bin@3.0.2 postinstall C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modul
es\jpegtran-bin
> node lib/install.js

  ‼ Request to https://raw.githubusercontent.com/imagemin/jpegtran-bin/3.0.2/vendor/win/x64/jpegtran.exe failed
  ‼ jpegtran pre-build test failed
  i compiling from source
  x Error: ./configure --disable-shared --prefix="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-jp
egtran\node_modules\jpegtran-bin\vendor" --bindir="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-j
pegtran\node_modules\jpegtran-bin\vendor" && make install
Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --disable-shared --prefix="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_m
odules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin\vendor" --bindir="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_
modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin\vendor""
'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)



> gifsicle@3.0.1 postinstall C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\g
ifsicle
> node lib/install.js

  ‼ Request to https://raw.githubusercontent.com/imagemin/gifsicle-bin/3.0.1/vendor/win/x64/gifsicle.exe failed
  ‼ gifsicle pre-build test failed
  i compiling from source
  x Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_mod
ules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\vendor" --bindir="C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_module
s\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\vendor" && make install
Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

And the output from my Grunt build

```
    Warning: Running "imagemin:dist" (imagemin) task
Warning: Error: spawn C:\local\GemStore\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-b
in\vendor\optipng.exe ENOENT in file app/images/yeoman.png Use --force to continue.
```

Any help will be greatly appreciated and please let me know if I need to provide more details.

**Comment by BenevidesLecontes** [comment]
I have this issue too.

 Execution Time (2015-07-06 13:01:58 UTC)
    loading tasks         136ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 49%
    loading grunt-svgmin   83ms  ▇▇▇▇▇▇▇▇▇▇▇▇ 30%
    svgmin:dist            59ms  ▇▇▇▇▇▇▇▇▇ 21%
    Total 278ms
        Warning: Running "imagemin:dist" (imagemin) task
    Warning: Error: Error: write EPIPE in file app/images/back.jpg Use --force to continue.
    
    Aborted due to warnings.
    
    
    Execution Time (2015-07-06 13:01:58 UTC)
    loading tasks                   139ms  ▇▇ 4%
    loading grunt-contrib-imagemin  300ms  ▇▇▇ 9%
    imagemin:dist                    2.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 87%
    Total 3.3s Use --force to continue.
        
        Aborted due to warnings.

**Comment by luckylooke** [comment]
ubuntu 14.04 64bit
```
 Warning: Running "imagemin:dist" (imagemin) task
    Warning: spawn /.../node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran ENOENT Use --force to continue.
    
    Aborted due to warnings.
```

**Comment by juristr** [comment]
:+1: same here, with Win7

**Comment by trevorhiley** [comment]
I'm having the same on osx Yosemite.

**Comment by annabellor** [comment]
I'm having the same.

imagemin: 0.9.4
node:v0.12.7
npm: v2.11.3

It works with:
imagemin: 0.9.2

**Comment by LaurentGoderre** [comment]
Same here on Ubuntu. The initial issue seems to be because the GitHub raw URL changed and perhaps the HTTP client doesn't follow redirects

**Comment by LaurentGoderre** [comment]
It's weird, it was working before but it's not working anymore

**Comment by LaurentGoderre** [comment]
It seems like this issue is only for Node 0.12. I tried installing in Node 0.10 and it installed fined (but I got a different error when the task ran) `Warning: Error: spawn ENOENT in file dist/theme-wet-boew/assets/favicon-mobile.png Use --force to continue.`

**Comment by LaurentGoderre** [comment]
Ok, after a full reinstall in Node 0.10 is working fine. Then a full reinstall in Node 0.12 and it's broken.

**Comment by LaurentGoderre** [comment]
Are any of your guys behind a proxy? I am wondering if this could be because of this. I am reading a lot of problems with Node 0.12 an proxies.

**Comment by LaurentGoderre** [comment]
THis copould be related https://github.com/librato/statsd-librato-backend/pull/54, they moved away from tunneled proxy in Node 0.12

**Comment by herrjosua** [comment]
I am not behind a proxy, as I am working locally. Although I will double check if I am using the https-proxy-agent in my code.

**Comment by woneob** [comment]
I have a similar issue as above. any help.

* OS: ubuntu 14.04 LTS
* node.js: 0.12.7
* grunt: 0.4.5
* grunt-contrib-imagemin: 0.9.4
```
Warning: Error: spawn /roor/app/app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_midules/gifsicle/vendor/gifsicle 
ENOENT in file src/image.gif Use --force to continue.

Aborted due to warnings.
```

**Comment by developeron29** [comment]
+1

**Comment by mostafabarmshory** [comment]
It is related to build a tool.  Some time node get C/C++ source code and try to build a project form the source. In the other hand node suppose GNU automake tools are installed.

You may solve it by installing MingW on windows.

**Comment by sindresorhus** [comment]
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.
