### ISSUE TITLE
Problems behind corporate proxy

### ISSUE THREAD

**Issue by kkoehler** [gruntjs/grunt-contrib-imagemin#315]
Hi,

we're working behind a proxy server. When running "npm install" we get the following error:

---
> jpegtran-bin@3.0.4 postinstall /home/user/dev/reference-trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Request to https://raw.github.com/imagemin/jpegtran-bin/3.0.4/vendor/linux/x64/jpegtran failed
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ GotError: Request to http://downloads.sourceforge.net/project/libjpeg-turbo/1.4.1/libjpeg-turbo-1.4.1.tar.gz failed
    at ClientRequest.<anonymous> (/home/user/dev/reference-trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/got/index.js:177:7)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:950:16
    at process._tickCallback (node.js:355:11)
Caused By: Error: getaddrinfo ENOTFOUND downloads.sourceforge.net
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
---

The http, http-proxy, etc are configured.
npm install itself works (I'm getting the grunt-contrib-imagemin module as you can see ;-))

Thanks,
Kristian

**Comment by sindresorhus** [comment]
Proxies are not currently supported: https://github.com/sindresorhus/got/issues/79

You can pass the `--ignore-scripts` flag to npm when installing to have it not run postinstall script that tries to download the binaries, but you'll then have to install them manually yourself.

**Comment by kevva** [comment]
Might be fixed in https://github.com/kevva/download/commit/c352736d7e484fdeba12a218d83227657bfd8ad4.
