### ISSUE TITLE
installation hanges on Centos

### ISSUE THREAD

**Issue by sjerman** [gruntjs/grunt-contrib-imagemin#336]
Hi,

Installing our build (npm install) build normally works fine (when run on Ubuntu or Mac. However, now unfortunately I need to run on Centos. It seems to hang installing grunt-contrib-imagemin:

Sometimes like this:

> optipng-bin@3.0.3 postinstall /home/wars/bsa/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js
(hang)

Sometimes like this:
> jpegtran-bin@3.0.6 postinstall /home/wars/bsa/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js
{hang)

I am running:
CentOS Linux release 7.1.1503 (Core) 
grunt-cli v0.1.13
grunt v0.4.5
node v0.12.7
npm 2.11.3

Any suggestions would be gratefully recieved.

**Comment by sjerman** [comment]
I've just tried the exact same thing on Ubuntu 14.04 and it hangs as well. I use a shrinkwrapped build config (attached). Something seems to have changed
[npm-shrinkwrap copy.txt](https://github.com/gruntjs/grunt-contrib-imagemin/files/39789/npm-shrinkwrap.copy.txt)

 very recently.

**Comment by sjerman** [comment]
OK... so discovered that the actual error is being hidden by my SSH connection timing out: below is what happens if it has a few hours to run.

I think I have seen this issue in another post... will investigate further.

Steve

> jpegtran-bin@3.0.6 postinstall /jenkins/workspace/team_prime-enterprise-network-automation/BSA-Build-and-Deploy/wars/bsa/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ socket hang up
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ RequestError: socket hang up
    at ClientRequest.<anonymous> (/jenkins/workspace/team_prime-enterprise-network-automation/BSA-Build-and-Deploy/wars/bsa/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/got/index.js:69:21)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:271:9)
    at TLSSocket.emit (events.js:107:17)
    at TLSSocket.onHangUp (_tls_wrap.js:964:16)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

> gifsicle@3.0.3 postinstall /jenkins/workspace/team_prime-enterprise-network-automation/BSA-Build-and-Deploy/wars/bsa/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ socket hang up
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ RequestError: write EPROTO 139922703390592:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:

    at ClientRequest.<anonymous> (/jenkins/workspace/team_prime-enterprise-network-automation/BSA-Build-and-Deploy/wars/bsa/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/got/index.js:69:21)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:271:9)
    at TLSSocket.emit (events.js:107:17)
    at onwriteError (_stream_writable.js:317:10)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at fireErrorCallbacks (net.js:456:13)
    at TLSSocket.Socket._destroy (net.js:495:3)
