### ISSUE TITLE
Artifactory as a proxy/cache for npm registry

### ISSUE THREAD

**Issue by JeanPerriault** [gruntjs/grunt-contrib-imagemin#382]
Hello,
I'm using artifactory as a proxy/cache for npm registry.
I want to avoid latency due to network, and one the bottleneck is the internal proxy.
So I've removed it from my .npmrc file.
When retrieving npm packages, I've got this error.

```
> gifsicle@3.0.4 postinstall C:\Users\Test\Workspace\test\node_modules\gifsicle
> node lib/install.js

  ‼ connect ETIMEDOUT 151.101.56.133:443
  ‼ gifsicle pre-build test failed
  i compiling from source
  × RequestError: connect ETIMEDOUT 192.30.253.113:443
    at ClientRequest.<anonymous> (C:\Users\Test\Workspace\test\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

> jpegtran-bin@3.2.0 postinstall C:\Users\Test\Workspace\test\node_modules\jpegtran-bin
> node lib/install.js

  ‼ connect ETIMEDOUT 151.101.56.133:443
  ‼ jpegtran pre-build test failed
  i compiling from source
  × RequestError: connect ETIMEDOUT 216.34.181.59:443
    at ClientRequest.<anonymous> (C:\Users\Test\Workspace\test\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

> optipng-bin@3.1.4 postinstall C:\Users\Test\Workspace\test\node_modules\optipng-bin
> node lib/install.js

  ‼ connect ETIMEDOUT 151.101.56.133:443
  ‼ optipng pre-build test failed
  i compiling from source
  × RequestError: connect ETIMEDOUT 216.34.181.59:443
    at ClientRequest.<anonymous> (C:\Users\Test\Workspace\test\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I've tried some workarounds:
* npm install globally "gifsicle", "jpegtran", "optipng"
* npm install dependencies "gifsicle", "jpegtran", "optipng"
* npm install dev dependencies for "imagemin-gifsicle", "imagemin-jpegtran", "imagemin-optipng"
* Install binaries of "gifsicle", adding exe in path
None of them was successful.

Env:
* Windows 10
* node 6.11.1
* npm 5.3.0

**Comment by JeanPerriault** [comment]
Maybe there is a link with https://github.com/npm/npm/issues/17025, but in this case internet proxy is set.

**Comment by sindresorhus** [comment]
Closing as no new features will be added to this plugin.

**Comment by subbiah28062** [comment]
I am facing this now, is there any solution. Exactly facing the same issue. we use private npm repository using npm config set registry https://npm.***.com
