### ISSUE TITLE
Error caminho não encontrado

### ISSUE THREAD

**Issue by Douglasfeuser** [gruntjs/grunt-contrib-imagemin#383]
Quando estou rodando a task do imagemin recebo essa msg.

Warning: Error: O sistema não pode encontrar o caminho especificado. in file 'exemplo' Use --force to continue.

Ainda não achei o que pode ser isso, gostaria de saber se vocês tem alguma solução.

**Comment by kevva** [comment]
> Warning: Error: The system can not find the path specified. in file 'example' Use --force to continue.

Seems pretty clear to me. Also, next time when opening an issue, please use English.

**Comment by Douglasfeuser** [comment]
Sorry for that, but still it is not the error here.
I have the file in the 'exemple/path.*{png}'

**Comment by andersonmadeira** [comment]
I'm also having the same issue with no solution at all. The file exists, but grunt keeps spawning that error message. I think it's really worth investigating the issue.

**Comment by andersonmadeira** [comment]
Is this related ?
```
‼ tunneling socket could not be established, cause=socket hang up
  ‼ jpegtran pre-build test failed
  i compiling from source
  × RequestError
    at ClientRequest.<anonymous> (C:\xampp\htdocs\etc\hello-grunt\node_modules\got\index.js:74:21)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at ClientRequest.onError (C:\xampp\htdocs\etc\hello-grunt\node_modules\tunnel-agent\index.js:178:21)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
```

I got this warning when installing grunt-contrib-imagemin but the main npm process did not issue any error, so I presumed the installation was successful

**Comment by blowsie** [comment]
Any solutions to this issue?

**Comment by blowsie** [comment]
```
Warning: Error: The system cannot find the path specified.
 in file dist/generic-mobile-pin-product/asda-mobile.jpg Use --force to continue.

Aborted due to warnings.

C:\x\images (develop) (images@1.0.0)
λ cd dist/generic-mobile-pin-product

C:\x\images\dist\generic-mobile-pin-product (develop) 
λ ls
asda-mobile.jpg  eon.png            lyca-mobile.jpg  orange.png       tesco-icc.jpg     three.png
asda-mobile.png  giffgaff.jpg       lyca-mobile.png  paysafecard.jpg  tesco-icc.png     virgin-mobile.jpg
ee.jpg           giffgaff.png       o2.jpg           paysafecard.png  tesco-mobile.jpg  virgin-mobile.png
ee.png           lebara-mobile.jpg  o2.png           t-mobile.jpg     tesco-mobile.png  vodafone.jpg
eon.jpg          lebara-mobile.png  orange.jpg       t-mobile.png     three.jpg         vodafone.png
```

**Comment by blowsie** [comment]
https://github.com/imagemin/imagemin/issues/209
