### ISSUE TITLE
Error with imagemin script in NPM

### ISSUE THREAD

**Issue by antoinecomp** [gruntjs/grunt-contrib-imagemin#386]
Hi there ! I am new to nodejs packet manager. I am following [a Coursera MOOC](https://www.coursera.org/learn/bootstrap-4/home/week/4) on Bootstrap4 from the University of Hong Kong.

#### I'm opening this issue because:

  - imagemin generates an error specific to a picture.

#### What's going wrong?

I wanted to build the distribution folder of a webpage following the instructions given on the npm scripts exerise page of the mooc.

When I try to execute the command npm run build I get errors with `imagemin img / * -o dist / img`.

The code is on [Bitbucket](https://bitbucket.org/AntoineCompagnie/bootstrap4)

I downloaded the latest version of npm and now I have:

```
    mike@mike-thinks:~/Bootstrap4/conFusion$ npm run build
    
    > confusion@1.0.0 build /home/mike/Bootstrap4/conFusion
    > npm run clean && npm run imagemin && npm run copyfonts && npm run usemin
    
    
    > confusion@1.0.0 clean /home/mike/Bootstrap4/conFusion
    > rimraf dist
    
    
    > confusion@1.0.0 imagemin /home/mike/Bootstrap4/conFusion
    > imagemin img/* -o dist/img
    
    Error: Error in file: img/logo.png
    
    spawn /usr/local/lib/node_modules/imagemin-cli/node_modules/optipng-bin/vendor/optipng ENOENT
        at _errnoException (util.js:1031:13)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
        at onErrorNT (internal/child_process.js:389:16)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! confusion@1.0.0 imagemin: `imagemin img/* -o dist/img`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the confusion@1.0.0 imagemin script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/mike/.npm/_logs/2017-12-27T11_42_38_033Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! confusion@1.0.0 build: `npm run clean && npm run imagemin && npm run copyfonts && npm run usemin`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the confusion@1.0.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/mike/.npm/_logs/2017-12-27T11_42_38_103Z-debug.log
```

Aqui estan el log para `imagemin: `imagemin img/* -o dist/img`, `2017-12-27T11_42_38_033Z-debug.log` :

```
    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'imagemin' ]
    2 info using npm@5.5.1
    3 info using node@v9.2.1
    4 verbose run-script [ 'preimagemin', 'imagemin', 'postimagemin' ]
    5 info lifecycle confusion@1.0.0~preimagemin: confusion@1.0.0
    6 info lifecycle confusion@1.0.0~imagemin: confusion@1.0.0
    7 verbose lifecycle confusion@1.0.0~imagemin: unsafe-perm in lifecycle true
    8 verbose lifecycle confusion@1.0.0~imagemin: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/mike/Bootstrap4/conFusion/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/mike/Bootstrap4/conFusion/node_modules/.bin:/home/mike/bin:/home/mike/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-version/bin:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin:/usr/local/hadoop/bin
    9 verbose lifecycle confusion@1.0.0~imagemin: CWD: /home/mike/Bootstrap4/conFusion
    10 silly lifecycle confusion@1.0.0~imagemin: Args: [ '-c', 'imagemin img/* -o dist/img' ]
    11 silly lifecycle confusion@1.0.0~imagemin: Returned: code: 1  signal: null
    12 info lifecycle confusion@1.0.0~imagemin: Failed to exec imagemin script
    13 verbose stack Error: confusion@1.0.0 imagemin: `imagemin img/* -o dist/img`
    13 verbose stack Exit status 1
    13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
    13 verbose stack     at EventEmitter.emit (events.js:159:13)
    13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    13 verbose stack     at ChildProcess.emit (events.js:159:13)
    13 verbose stack     at maybeClose (internal/child_process.js:943:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
    14 verbose pkgid confusion@1.0.0
    15 verbose cwd /home/mike/Bootstrap4/conFusion
    16 verbose Linux 4.10.0-42-generic
    17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "imagemin"
    18 verbose node v9.2.1
    19 verbose npm  v5.5.1
    20 error code ELIFECYCLE
    21 error errno 1
    22 error confusion@1.0.0 imagemin: `imagemin img/* -o dist/img`
    22 error Exit status 1
    23 error Failed at the confusion@1.0.0 imagemin script.
    23 error This is probably not a problem with npm. There is likely additional logging output above.
    24 verbose exit [ 1, true ]

```
And the log for `confusion@1.0.0 build script`, `2017-12-27T11_42_38_103Z-debug.log`

```
    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
    2 info using npm@5.5.1
    3 info using node@v9.2.1
    4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
    5 info lifecycle confusion@1.0.0~prebuild: confusion@1.0.0
    6 info lifecycle confusion@1.0.0~build: confusion@1.0.0
    7 verbose lifecycle confusion@1.0.0~build: unsafe-perm in lifecycle true
    8 verbose lifecycle confusion@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/mike/Bootstrap4/conFusion/node_modules/.bin:/home/mike/bin:/home/mike/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-version/bin:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin:/usr/local/hadoop/bin
    9 verbose lifecycle confusion@1.0.0~build: CWD: /home/mike/Bootstrap4/conFusion
    10 silly lifecycle confusion@1.0.0~build: Args: [ '-c',
    10 silly lifecycle   'npm run clean && npm run imagemin && npm run copyfonts && npm run usemin' ]
    11 silly lifecycle confusion@1.0.0~build: Returned: code: 1  signal: null
    12 info lifecycle confusion@1.0.0~build: Failed to exec build script
    13 verbose stack Error: confusion@1.0.0 build: `npm run clean && npm run imagemin && npm run copyfonts && npm run usemin`
    13 verbose stack Exit status 1
    13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
    13 verbose stack     at EventEmitter.emit (events.js:159:13)
    13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    13 verbose stack     at ChildProcess.emit (events.js:159:13)
    13 verbose stack     at maybeClose (internal/child_process.js:943:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
    14 verbose pkgid confusion@1.0.0
    15 verbose cwd /home/mike/Bootstrap4/conFusion
    16 verbose Linux 4.10.0-42-generic
    17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
    18 verbose node v9.2.1
    19 verbose npm  v5.5.1
    20 error code ELIFECYCLE
    21 error errno 1
    22 error confusion@1.0.0 build: `npm run clean && npm run imagemin && npm run copyfonts && npm run usemin`
    22 error Exit status 1
    23 error Failed at the confusion@1.0.0 build script.
    23 error This is probably not a problem with npm. There is likely additional logging output above.
    24 verbose exit [ 1, true ]
```

### Child process investigation

I went to see if there was a problem with the child process (this case imagemin). It did not end with a status code of 0. I ran the imagemin command img / * -o dist / img on the terminal so I can see if it is sending an error message to the terminal. He answered me:

```
mike@mike-thinks:~/Bootstrap4/conFusion$ imagemin img/* -o dist/img
Error: Error in file: img/alberto.png

spawn /usr/local/lib/node_modules/imagemin-cli/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by XhmikosR** [comment]
Something seems to have been wrong when doing `npm i`. You should make sure you are on the latest Node.js (and thus npm) and try again.

**Comment by soso-maitha** [comment]
i am getting error, I am stuck in my work. I already updated npm but still issue not resolved!
