### ISSUE TITLE
node-gyp grunt installation angularjs 

### ISSUE THREAD

**Issue by Salaheddinezafati** [gruntjs/grunt-contrib-imagemin#399]
this my errors when i want to install packages with npm install i think i missing something in the installation for node-gyp

npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated uuid@1.4.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.      

> ws@0.4.32 install D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> phantomjs@1.9.20 install D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\MSISOS~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\MSISOS~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1681306000184\phantomjs-1.9.8-windows -> D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\phantomjs\lib\phantom\phantomjs.exe

> es5-ext@0.10.62 postinstall D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0

> jpegtran-bin@0.2.8 postinstall D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
> node index.js

internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:124:11)
    at Object.basename (path.js:743:5)
    at D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\download\index.js:35:43
    at each (D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\each-async\each-async.js:63:4)
    at module.exports (D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\download\index.js:33:5)
    at D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\bin-wrapper\index.js:108:20
    at D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\bin-wrapper\index.js:141:24
    at D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\bin-check\index.js:30:20
    at D:\dxc\document\ngfolder\PharosApp\sigma-parent\sigma-ng\node_modules\executable\index.js:39:20
    at FSReqCallback.oncomplete (fs.js:192:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm WARN sigmang@0.0.0 No repository field.
npm WARN sigmang@0.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jpegtran-bin@0.2.8 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jpegtran-bin@0.2.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MSI SOS\AppData\Roaming\npm-cache\_logs\2023-04-12T13_26_41_560Z-debug.log

**Comment by Salaheddinezafati** [comment]
help me
